name: Release

on:
  push:
    tag:
      - '*'

jobs:
  run-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create release
        run: mv text text_${GITHUB_REF_NAME}
      - uses: actions/upload-artifact@master
        with:
          name: text_${{ github.ref_name }}
          path: text_${{ github.ref_name }}
          if-no-files-found: error

